# Generated by Django 4.1.1 on 2022-12-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_imagm_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='imagm_receita',
            new_name='imagem_receita',
        ),
    ]
