# Generated by Django 4.1.7 on 2023-03-16 11:23

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [

        ('receitas', '0005_auto_20191219_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='date_receita',
            new_name='data_receita',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='foto_receita',
            new_name='imagem_receita',
        ),
        migrations.AlterField(
            model_name='receita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receita',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
